name: Cypress teste

on:
  workflow_dispath:
    inputs:
      cli:
        description: run by cypress command line
        default: yarn cypress run

jobs: 
  cypress-electron-test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
       
    
        
      
